// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantReservation.Db;

#nullable disable

namespace RestaurantReservation.Db.Migrations
{
    [DbContext(typeof(RestaurantReservationDbContext))]
    [Migration("20260811081924_UseDateTimeOffsetForDates")]
    partial class UseDateTimeOffsetForDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "555-1001",
                            RowVersion = new byte[0],
                            UserId = 1
                        },
                        new
                        {
                            CustomerId = 2,
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "555-1002",
                            RowVersion = new byte[0],
                            UserId = 2
                        },
                        new
                        {
                            CustomerId = 3,
                            Email = "michael.johnson@example.com",
                            FirstName = "Michael",
                            LastName = "Johnson",
                            PhoneNumber = "555-1003",
                            RowVersion = new byte[0],
                            UserId = 3
                        },
                        new
                        {
                            CustomerId = 4,
                            Email = "emily.davis@example.com",
                            FirstName = "Emily",
                            LastName = "Davis",
                            PhoneNumber = "555-1004",
                            RowVersion = new byte[0],
                            UserId = 4
                        },
                        new
                        {
                            CustomerId = 5,
                            Email = "david.wilson@example.com",
                            FirstName = "David",
                            LastName = "Wilson",
                            PhoneNumber = "555-1005",
                            RowVersion = new byte[0],
                            UserId = 5
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            FirstName = "Alice",
                            LastName = "Turner",
                            Position = "Manager",
                            RestaurantId = 1,
                            RowVersion = new byte[0],
                            UserId = 6
                        },
                        new
                        {
                            EmployeeId = 2,
                            FirstName = "Bob",
                            LastName = "Cook",
                            Position = "VipOrdersWaiter",
                            RestaurantId = 1,
                            RowVersion = new byte[0],
                            UserId = 7
                        },
                        new
                        {
                            EmployeeId = 3,
                            FirstName = "Carol",
                            LastName = "White",
                            Position = "Manager",
                            RestaurantId = 2,
                            RowVersion = new byte[0],
                            UserId = 8
                        },
                        new
                        {
                            EmployeeId = 4,
                            FirstName = "Dan",
                            LastName = "Brown",
                            Position = "StandardWaiter",
                            RestaurantId = 2,
                            RowVersion = new byte[0],
                            UserId = 9
                        },
                        new
                        {
                            EmployeeId = 5,
                            FirstName = "Eve",
                            LastName = "Black",
                            Position = "Manager",
                            RestaurantId = 3,
                            RowVersion = new byte[0],
                            UserId = 10
                        },
                        new
                        {
                            EmployeeId = 6,
                            FirstName = "Frank",
                            LastName = "Green",
                            Position = "AssistantWaiter",
                            RestaurantId = 4,
                            RowVersion = new byte[0],
                            UserId = 11
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.MenuItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ItemId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuItems", t =>
                        {
                            t.HasCheckConstraint("CK_MenuItems_PriceIsNotNegative", "[Price] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Description = "Atlantic salmon with lemon butter",
                            Name = "Grilled Salmon",
                            Price = 24.99m,
                            RestaurantId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            ItemId = 2,
                            Description = "Romaine, parmesan, croutons",
                            Name = "Caesar Salad",
                            Price = 12.50m,
                            RestaurantId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            ItemId = 3,
                            Description = "Tomato, mozzarella, basil",
                            Name = "Margherita Pizza",
                            Price = 15.00m,
                            RestaurantId = 2,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            ItemId = 4,
                            Description = "Egg, pancetta, pecorino",
                            Name = "Spaghetti Carbonara",
                            Price = 17.50m,
                            RestaurantId = 2,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            ItemId = 5,
                            Description = "Chef's selection of 12 pieces",
                            Name = "Sushi Platter",
                            Price = 29.99m,
                            RestaurantId = 3,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            ItemId = 6,
                            Description = "Slow-braised beef in red wine",
                            Name = "Beef Bourguignon",
                            Price = 26.00m,
                            RestaurantId = 4,
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("EmployeeId", "RestaurantId");

                    b.HasIndex("ReservationId", "RestaurantId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            EmployeeId = 1,
                            OrderDate = new DateTimeOffset(new DateTime(2026, 8, 1, 19, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReservationId = 1,
                            RestaurantId = 1,
                            RowVersion = new byte[0],
                            TotalAmount = 37.49m
                        },
                        new
                        {
                            OrderId = 2,
                            EmployeeId = 2,
                            OrderDate = new DateTimeOffset(new DateTime(2026, 8, 1, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReservationId = 1,
                            RestaurantId = 1,
                            RowVersion = new byte[0],
                            TotalAmount = 24.99m
                        },
                        new
                        {
                            OrderId = 3,
                            EmployeeId = 1,
                            OrderDate = new DateTimeOffset(new DateTime(2026, 8, 2, 20, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReservationId = 2,
                            RestaurantId = 1,
                            RowVersion = new byte[0],
                            TotalAmount = 49.98m
                        },
                        new
                        {
                            OrderId = 4,
                            EmployeeId = 3,
                            OrderDate = new DateTimeOffset(new DateTime(2026, 8, 3, 19, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReservationId = 3,
                            RestaurantId = 2,
                            RowVersion = new byte[0],
                            TotalAmount = 32.50m
                        },
                        new
                        {
                            OrderId = 5,
                            EmployeeId = 5,
                            OrderDate = new DateTimeOffset(new DateTime(2026, 8, 4, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReservationId = 4,
                            RestaurantId = 3,
                            RowVersion = new byte[0],
                            TotalAmount = 29.99m
                        },
                        new
                        {
                            OrderId = 6,
                            EmployeeId = 6,
                            OrderDate = new DateTimeOffset(new DateTime(2026, 8, 5, 20, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReservationId = 5,
                            RestaurantId = 4,
                            RowVersion = new byte[0],
                            TotalAmount = 26.00m
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("ItemId", "RestaurantId");

                    b.HasIndex("OrderId", "RestaurantId");

                    b.ToTable("OrderItems", t =>
                        {
                            t.HasCheckConstraint("CK_OrderItems_QuantityIsPositive", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_OrderItems_UnitPriceIsNotNegative", "[UnitPrice] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            OrderItemId = 1,
                            ItemId = 1,
                            OrderId = 1,
                            Quantity = 1,
                            RestaurantId = 1,
                            RowVersion = new byte[0],
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            OrderItemId = 2,
                            ItemId = 2,
                            OrderId = 1,
                            Quantity = 1,
                            RestaurantId = 1,
                            RowVersion = new byte[0],
                            UnitPrice = 12.50m
                        },
                        new
                        {
                            OrderItemId = 3,
                            ItemId = 1,
                            OrderId = 2,
                            Quantity = 1,
                            RestaurantId = 1,
                            RowVersion = new byte[0],
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            OrderItemId = 4,
                            ItemId = 1,
                            OrderId = 3,
                            Quantity = 2,
                            RestaurantId = 1,
                            RowVersion = new byte[0],
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            OrderItemId = 5,
                            ItemId = 3,
                            OrderId = 4,
                            Quantity = 1,
                            RestaurantId = 2,
                            RowVersion = new byte[0],
                            UnitPrice = 15.00m
                        },
                        new
                        {
                            OrderItemId = 6,
                            ItemId = 4,
                            OrderId = 4,
                            Quantity = 1,
                            RestaurantId = 2,
                            RowVersion = new byte[0],
                            UnitPrice = 17.50m
                        },
                        new
                        {
                            OrderItemId = 7,
                            ItemId = 5,
                            OrderId = 5,
                            Quantity = 1,
                            RestaurantId = 3,
                            RowVersion = new byte[0],
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            OrderItemId = 8,
                            ItemId = 6,
                            OrderId = 6,
                            Quantity = 1,
                            RestaurantId = 4,
                            RowVersion = new byte[0],
                            UnitPrice = 26.00m
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("PartySize")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ReservationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TableCapacity")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("TableId", "ReservationDate")
                        .IsUnique();

                    b.HasIndex("TableId", "RestaurantId", "TableCapacity");

                    b.ToTable("Reservations", t =>
                        {
                            t.HasCheckConstraint("CK_Reservations_PartySizeIsPositive", "[PartySize] > 0");

                            t.HasCheckConstraint("CK_Reservations_PartySizeWithinTableCapacity", "[PartySize] <= [TableCapacity]");

                            t.HasCheckConstraint("CK_Reservations_ReservationDateOnTheHour", "DATEPART(MINUTE, [ReservationDate]) = 0 AND DATEPART(SECOND, [ReservationDate]) = 0 AND DATEPART(NANOSECOND, [ReservationDate]) = 0");
                        });

                    b.HasData(
                        new
                        {
                            ReservationId = 1,
                            CustomerId = 1,
                            PartySize = 2,
                            ReservationDate = new DateTimeOffset(new DateTime(2026, 8, 1, 19, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RestaurantId = 1,
                            RowVersion = new byte[0],
                            TableCapacity = 2,
                            TableId = 1
                        },
                        new
                        {
                            ReservationId = 2,
                            CustomerId = 2,
                            PartySize = 4,
                            ReservationDate = new DateTimeOffset(new DateTime(2026, 8, 2, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RestaurantId = 1,
                            RowVersion = new byte[0],
                            TableCapacity = 4,
                            TableId = 2
                        },
                        new
                        {
                            ReservationId = 3,
                            CustomerId = 3,
                            PartySize = 3,
                            ReservationDate = new DateTimeOffset(new DateTime(2026, 8, 3, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RestaurantId = 2,
                            RowVersion = new byte[0],
                            TableCapacity = 4,
                            TableId = 3
                        },
                        new
                        {
                            ReservationId = 4,
                            CustomerId = 4,
                            PartySize = 6,
                            ReservationDate = new DateTimeOffset(new DateTime(2026, 8, 4, 19, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RestaurantId = 3,
                            RowVersion = new byte[0],
                            TableCapacity = 6,
                            TableId = 4
                        },
                        new
                        {
                            ReservationId = 5,
                            CustomerId = 5,
                            PartySize = 2,
                            ReservationDate = new DateTimeOffset(new DateTime(2026, 8, 5, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RestaurantId = 4,
                            RowVersion = new byte[0],
                            TableCapacity = 2,
                            TableId = 5
                        },
                        new
                        {
                            ReservationId = 6,
                            CustomerId = 1,
                            PartySize = 8,
                            ReservationDate = new DateTimeOffset(new DateTime(2026, 8, 6, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RestaurantId = 5,
                            RowVersion = new byte[0],
                            TableCapacity = 8,
                            TableId = 6
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Address = "123 Main St, Springfield",
                            Name = "The Gourmet Kitchen",
                            OpeningHours = "10:00-23:00",
                            PhoneNumber = "555-0101",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            RestaurantId = 2,
                            Address = "45 Oak Avenue, Springfield",
                            Name = "Bella Italia",
                            OpeningHours = "11:00-22:00",
                            PhoneNumber = "555-0102",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            RestaurantId = 3,
                            Address = "9 River Road, Shelbyville",
                            Name = "Sushi Zen",
                            OpeningHours = "12:00-22:30",
                            PhoneNumber = "555-0103",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            RestaurantId = 4,
                            Address = "78 Elm Street, Shelbyville",
                            Name = "Le Petite Bistro",
                            OpeningHours = "17:00-23:30",
                            PhoneNumber = "555-0104",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            RestaurantId = 5,
                            Address = "200 Grand Blvd, Capital City",
                            Name = "The Steakhouse",
                            OpeningHours = "16:00-00:00",
                            PhoneNumber = "555-0105",
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("TableId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Tables", t =>
                        {
                            t.HasCheckConstraint("CK_Tables_CapacityIsPositive", "[Capacity] > 0");
                        });

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            Capacity = 2,
                            RestaurantId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            TableId = 2,
                            Capacity = 4,
                            RestaurantId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            TableId = 3,
                            Capacity = 4,
                            RestaurantId = 2,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            TableId = 4,
                            Capacity = 6,
                            RestaurantId = 3,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            TableId = 5,
                            Capacity = 2,
                            RestaurantId = 4,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            TableId = 6,
                            Capacity = 8,
                            RestaurantId = 5,
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEIBPg0ewhJ5n53xz44KlYSSDvhwxyBuRtzQ+ytXmpEao5y/dmWmFOp9jKOJa7ux+bQ==",
                            RowVersion = new byte[0],
                            Username = "john.doe"
                        },
                        new
                        {
                            UserId = 2,
                            PasswordHash = "AQAAAAIAAYagAAAAEDm7Y7HkVS/kaIjfrvDj74Oca+8J1GYa7mpUjuUg2ag4HQvo4Jk6tIm47/VGnbmkyw==",
                            RowVersion = new byte[0],
                            Username = "jane.smith"
                        },
                        new
                        {
                            UserId = 3,
                            PasswordHash = "AQAAAAIAAYagAAAAEKBdwZsSAeO6CJrYUhTx74qhMv3YxDO/loMRtHxIs7XFN51qIocdI9jRe0Q98PYOTQ==",
                            RowVersion = new byte[0],
                            Username = "michael.johnson"
                        },
                        new
                        {
                            UserId = 4,
                            PasswordHash = "AQAAAAIAAYagAAAAEOTo3Ly50M1eu49u3Mf9qr+NkRO2QRWcNRjZDqBUfNRLz0gEgCsSS4dm4a7B6TCJJg==",
                            RowVersion = new byte[0],
                            Username = "emily.davis"
                        },
                        new
                        {
                            UserId = 5,
                            PasswordHash = "AQAAAAIAAYagAAAAEBKJGhoqk3DWchXBg6SQULteviXT1GatQtEXHqWnto6/LBam3IdGQWDibFUgf/yk1w==",
                            RowVersion = new byte[0],
                            Username = "david.wilson"
                        },
                        new
                        {
                            UserId = 6,
                            PasswordHash = "AQAAAAIAAYagAAAAENo/A93E/1FhZg8+OAnOLm70xAqSjW6clyn4AJIpCH4GcsBwuJaxf5UEA2oZ4UQjSQ==",
                            RowVersion = new byte[0],
                            Username = "alice.turner"
                        },
                        new
                        {
                            UserId = 7,
                            PasswordHash = "AQAAAAIAAYagAAAAEExphGBVuZExPZTlHQ6hQO1GT+nyON6koGot2siIyRA1lE1WzPDn0h1xXAXbpR3Yjw==",
                            RowVersion = new byte[0],
                            Username = "bob.cook"
                        },
                        new
                        {
                            UserId = 8,
                            PasswordHash = "AQAAAAIAAYagAAAAELVW31dCx40O1GBijQ7Upeu9sGZVfCHyQhBLqGR7P9vXO0hcsmrRNx8uuhNB2zQ61Q==",
                            RowVersion = new byte[0],
                            Username = "carol.white"
                        },
                        new
                        {
                            UserId = 9,
                            PasswordHash = "AQAAAAIAAYagAAAAEDrJQV8EwE1UtxJtz6GE2j0AHcNTlzBiFcKt8cwXwWC3oBHA95ImfdMgaeXnZs8IRQ==",
                            RowVersion = new byte[0],
                            Username = "dan.brown"
                        },
                        new
                        {
                            UserId = 10,
                            PasswordHash = "AQAAAAIAAYagAAAAEMgwF8w+eAczEKjurnAoIhjX+BxqRpaZxALyFd3XRU3UIcMI/MVHMQRmLPwmkDSX5Q==",
                            RowVersion = new byte[0],
                            Username = "eve.black"
                        },
                        new
                        {
                            UserId = 11,
                            PasswordHash = "AQAAAAIAAYagAAAAEP0ocSpAttnNpNcwKkhuNIFho6xB3NNWy/FFZp/XaKuS5p3uUkeQ3DfjfmQ/klby4g==",
                            RowVersion = new byte[0],
                            Username = "frank.green"
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Views.EmployeeRestaurantDetail", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantOpeningHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_EmployeeDetails", (string)null);
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Views.ReservationDetail", b =>
                {
                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartySize")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ReservationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("RestaurantAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_ReservationDetails", (string)null);
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Customer", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Entities.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("RestaurantReservation.Db.Entities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Employee", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Entities.Restaurant", "Restaurant")
                        .WithMany("Employees")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantReservation.Db.Entities.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("RestaurantReservation.Db.Entities.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.MenuItem", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Entities.Restaurant", "Restaurant")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Order", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Entities.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId", "RestaurantId")
                        .HasPrincipalKey("EmployeeId", "RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantReservation.Db.Entities.Reservation", "Reservation")
                        .WithMany("Orders")
                        .HasForeignKey("ReservationId", "RestaurantId")
                        .HasPrincipalKey("ReservationId", "RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.OrderItem", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Entities.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemId", "RestaurantId")
                        .HasPrincipalKey("ItemId", "RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantReservation.Db.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId", "RestaurantId")
                        .HasPrincipalKey("OrderId", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Reservation", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Entities.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantReservation.Db.Entities.Restaurant", "Restaurant")
                        .WithMany("Reservations")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantReservation.Db.Entities.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId", "RestaurantId", "TableCapacity")
                        .HasPrincipalKey("TableId", "RestaurantId", "Capacity")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Restaurant");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Table", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Entities.Restaurant", "Restaurant")
                        .WithMany("Tables")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Employee", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Reservation", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Restaurant", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("MenuItems");

                    b.Navigation("Reservations");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.Table", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Entities.User", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
