using RestaurantReservation.Db.Entities;
using RestaurantReservation.Db.Results;

namespace RestaurantReservation.Db.Abstractions;

public interface IRestaurantRepository : IRepository<Restaurant>
{
    /// <summary>
    /// Calculates the total revenue generated by a restaurant by invoking the <c>dbo.fn_CalculateRestaurantRevenue</c> SQL scalar function.
    /// A restaurant that does not exist is reported as <see cref="ErrorType.NotFound" />.
    /// </summary>
    Task<Result<decimal>> GetTotalRevenueAsync(int restaurantId, CancellationToken cancellationToken = default);
}
