using RestaurantReservation.Db.Entities;

namespace RestaurantReservation.Db.Abstractions;

public interface IRestaurantRepository : IRepository<Restaurant>
{
    /// <summary>
    /// Calculates the total revenue generated by a restaurant by invoking the <c>dbo.fn_CalculateRestaurantRevenue</c> SQL scalar function.
    /// </summary>
    Task<decimal> GetTotalRevenueAsync(int restaurantId, CancellationToken cancellationToken = default);
}